- .idea/modules/modules/cli/modules_cli.iml
- .idea/modules/modules/cli/modules_cli_main.iml
- .idea/modules/modules/cli/modules_cli_test.iml
- .idea/modules/modules/lib/modules_lib.iml
- .idea/modules/modules/lib/modules_lib_main.iml
- .idea/modules/modules/lib/modules_lib_test.iml
- build.gradle
- modules/lib/src/main/java/com/jaffsoft/openapistylevalidator/OpenApiSpecStyleValidator.java
- modules/lib/src/main/java/com/jaffsoft/openapistylevalidator/ValidatorParameters.java
- modules/lib/src/test/java/com/jaffsoft/openapistylevalidator/ValidatorParametersTest.java
- specs/options.json
Add a new parameters to ignore headers starting with "X-" because most of the time, they are "standard" and must follow other convention.
> Add a parameter to ignore header param starting with "X-"

- .idea/modules.xml
- .idea/runConfigurations/All_Tests.xml
- .idea/runConfigurations/Run.xml
- README.md
- build.gradle
- modules/cli/src/main/java/org/openapitools/openapistylevalidator/Main.java
- modules/lib/src/main/java/org/openapitools/openapistylevalidator/ErrorAggregator.java
- modules/lib/src/main/java/org/openapitools/openapistylevalidator/NamingValidator.java
- modules/lib/src/main/java/org/openapitools/openapistylevalidator/OpenApiSpecStyleValidator.java
- modules/lib/src/main/java/org/openapitools/openapistylevalidator/ValidatorParameters.java
- modules/lib/src/main/java/org/openapitools/openapistylevalidator/commons/Utils.java
- modules/lib/src/main/java/org/openapitools/openapistylevalidator/styleerror/GenericStyleError.java
- modules/lib/src/main/java/org/openapitools/openapistylevalidator/styleerror/ModelNamingStyleError.java
- modules/lib/src/main/java/org/openapitools/openapistylevalidator/styleerror/ModelStyleError.java
- modules/lib/src/main/java/org/openapitools/openapistylevalidator/styleerror/OperationNamingStyleError.java
- modules/lib/src/main/java/org/openapitools/openapistylevalidator/styleerror/OperationStyleError.java
- modules/lib/src/main/java/org/openapitools/openapistylevalidator/styleerror/StyleError.java
- modules/lib/src/test/java/org/openapitools/openapistylevalidator/ErrorAggregatorTest.java
- modules/lib/src/test/java/org/openapitools/openapistylevalidator/NamingValidatorTest.java
- modules/lib/src/test/java/org/openapitools/openapistylevalidator/ValidatorParametersTest.java
Fix #6. Remove JaffSoft everywhere and add notice
> Fix #6. Remove JaffSoft everywhere and add notice

- .idea/compiler.xml
- .idea/modules/cli/cli.iml
- .idea/modules/cli/cli_main.iml
- .idea/modules/cli/cli_test.iml
- .idea/modules/lib/lib.iml
- .idea/modules/lib/lib_main.iml
- .idea/modules/lib/lib_test.iml
- .idea/modules/openapi-style-validator.iml
- README.md
- build.gradle
- cli/build.gradle
Use shadow jar + configuration of the gradle files
> Fix #17 : Use shadowJar instead of default one

- build.gradle
- cli/build.gradle
- lib/build.gradle
Add signing as additional step: signing
This is required to publish to maven central.
Related issue #10
> Add signing task

- .idea/modules/cli/cli.iml
- .idea/modules/cli/cli_main.iml
- .idea/modules/cli/cli_test.iml
- .idea/modules/lib/lib.iml
- .idea/modules/lib/lib_main.iml
- .idea/modules/lib/lib_test.iml
- .idea/modules/openapi-style-validator.iml
- .idea/runConfigurations/Run_help.xml
- .idea/runConfigurations/Run_no_argument.xml
- .idea/uiDesigner.xml
- cli/src/main/java/org/openapitools/openapistylevalidator/Main.java
- cli/src/main/java/org/openapitools/openapistylevalidator/OptionManager.java
- cli/src/main/java/org/openapitools/openapistylevalidator/OutputUtils.java
Small refactoring of the options to fix #33
> Fix #33 default options + help

- .idea/modules/lib/lib_test.iml
- lib/build.gradle
- lib/src/main/java/org/openapitools/openapistylevalidator/OpenApiSpecStyleValidator.java
- lib/src/test/java/org/openapitools/openapistylevalidator/OpenApiSpecStyleValidatorTest.java
> Fix NullPointerException when components is null

- cli/src/main/java/org/openapitools/openapistylevalidator/cli/Main.java
- cli/src/main/java/org/openapitools/openapistylevalidator/cli/OptionManager.java
- cli/src/main/java/org/openapitools/openapistylevalidator/cli/OutputUtils.java
- lib/src/main/java/org/openapitools/openapistylevalidator/OpenApiSpecStyleValidator.java
- lib/src/main/java/org/openapitools/openapistylevalidator/ValidatorParameters.java
> Change main package of cli module

- .idea/runConfigurations/Run.xml
- .idea/runConfigurations/RunSplit.xml
- .idea/runConfigurations/RunV3.xml
- .idea/runConfigurations/Run_help.xml
- .idea/runConfigurations/Run_no_argument.xml
- .travis.yml
- README.md
- build.gradle
~~WIP, please do not merge. Need to test the CI result.~~
> Fix #42: Tentative to add code coverage with codecov + jacoco + badge

- lib/src/main/java/org/openapitools/openapistylevalidator/ValidatorParameters.java
As a follow up of #39, the getters/setters in `ValidatorParameters` should be public.
> Make ValidatorParameters public

- README.md
Update the corresponding section in the README.
> Add section about released artifacts on maven central

- cli/src/test/java/org/openapitools/openapistylevalidator/cli/MainTest.java
- cli/src/test/resources/alternative.json
- cli/src/test/resources/some.yaml
- cli/src/test/resources/underscore.json
- lib/src/main/java/org/openapitools/openapistylevalidator/OpenApiSpecStyleValidator.java
> Fix path naming validation

- README.md
- cli/src/main/java/org/openapitools/openapistylevalidator/cli/OptionManager.java
- cli/src/test/java/org/openapitools/openapistylevalidator/cli/MainTest.java
- cli/src/test/resources/alternative.json
- cli/src/test/resources/alternativeAndLegacy.json
- cli/src/test/resources/alternativeLegacy.json
- cli/src/test/resources/default.json
- cli/src/test/resources/underscore.json
- cli/src/test/resources/underscoreLegacy.json
- lib/src/main/java/org/openapitools/openapistylevalidator/NamingValidator.java
- lib/src/main/java/org/openapitools/openapistylevalidator/OpenApiSpecStyleValidator.java
- lib/src/main/java/org/openapitools/openapistylevalidator/ValidatorParameters.java
- lib/src/test/java/org/openapitools/openapistylevalidator/NamingValidatorTest.java
- lib/src/test/java/org/openapitools/openapistylevalidator/ValidatorParametersTest.java
> Rename "Naming Strategy" to "Naming Convention"

- .idea/compiler.xml
- .idea/gradle.xml
- .idea/jarRepositories.xml
- .idea/modules.xml
- .idea/modules/cli/cli.iml
- .idea/modules/cli/cli_main.iml
- .idea/modules/gradle-plugin/gradle-plugin.iml
- .idea/modules/gradle-plugin/gradle-plugin_functionalTest.iml
- .idea/modules/gradle-plugin/gradle-plugin_main.iml
- .idea/modules/gradle-plugin/gradle-plugin_test.iml
- .idea/modules/lib/lib.iml
- .idea/modules/lib/lib_main.iml
- .idea/modules/lib/lib_test.iml
- .idea/modules/openapi-style-validator.iml
- gradle-plugin/build.gradle
- gradle-plugin/src/functionalTest/java/org/openapitools/openapistylevalidator/gradle/OpenAPIStyleValidatorGradlePluginFunctionalTest.java
- gradle-plugin/src/main/java/org/openapitools/openapistylevalidator/gradle/OpenAPIStyleValidatorGradlePlugin.java
- gradle-plugin/src/main/java/org/openapitools/openapistylevalidator/gradle/OpenAPIStyleValidatorTask.java
- gradle-plugin/src/test/java/org/openapitools/openapistylevalidator/gradle/OpenAPIStyleValidatorGradlePluginTest.java
- settings.gradle
See issue #20, this PR adds a gradle-plugin module
> Initial version of the gradle-plugin

- README.md
- cli/build.gradle
Fixes #75 by setting back the classifier explicitly to `all`.
> Set the classifier for the shadowJar

- .github/workflows/sonar.yml
- .idea/sonarlint-state.xml
- .idea/sonarlint.xml
- .idea/vcs.xml
- build.gradle
- sonar-project-properties
Tentative. Was crashing on my computer, want to see if it works directly with the CI
> fix #86: Add sonar scan to the CI

- cli/build.gradle
- gradle-plugin/build.gradle
- lib/build.gradle
- maven-plugin/build.gradle
And update 'empoa' to version '2.0.0' to stay compatible with this version
> Update 'microprofile-openapi-api' to version '2.0'

- cli/src/main/java/org/openapitools/openapistylevalidator/cli/OptionManager.java
> Handle JsonSyntaxException in OptionManager

- README.md
- build.gradle
- cli/src/test/java/org/openapitools/openapistylevalidator/cli/MainTest.java
- cli/src/test/resources/default.json
- gradle-plugin/src/main/java/org/openapitools/openapistylevalidator/gradle/OpenAPIStyleValidatorTask.java
- lib/src/main/java/org/openapitools/openapistylevalidator/ErrorAggregator.java
- lib/src/main/java/org/openapitools/openapistylevalidator/OpenApiSpecStyleValidator.java
- lib/src/main/java/org/openapitools/openapistylevalidator/ValidatorParameters.java
- lib/src/main/java/org/openapitools/openapistylevalidator/styleerror/ModelStyleError.java
- lib/src/test/java/org/openapitools/openapistylevalidator/ErrorAggregatorTest.java
- lib/src/test/java/org/openapitools/openapistylevalidator/OpenApiSpecStyleValidatorTest.java
- lib/src/test/java/org/openapitools/openapistylevalidator/TestDataProvider.java
- lib/src/test/java/org/openapitools/openapistylevalidator/ValidatorParametersTest.java
- lib/src/test/java/org/openapitools/openapistylevalidator/styleerror/ModelStyleErrorTest.java
- maven-plugin/src/main/java/org/openapitools/openapistylevalidator/maven/OpenAPIStyleValidatorMojo.java
- specs/options.json
> Validate model required properties

- maven-plugin/src/main/java/org/openapitools/openapistylevalidator/maven/OpenAPIStyleValidatorMojo.java
> Maven generates warnings during parallel builds

- maven-plugin/src/main/java/org/openapitools/openapistylevalidator/maven/OpenAPIStyleValidatorMojo.java
> Maven default plugin phase

- .github/workflows/documentation.yml
- website/docusaurus.config.js
> Fix #83: Add automatic deploy of the documentation

- lib/build.gradle
- lib/src/main/java/org/openapitools/openapistylevalidator/ErrorMessageHelper.java
- lib/src/main/java/org/openapitools/openapistylevalidator/commons/OpenAPIUtils.java
- lib/src/main/java/org/openapitools/openapistylevalidator/rules/ContactInfoRule.java
- lib/src/main/java/org/openapitools/openapistylevalidator/rules/InfoDescriptionRule.java
- lib/src/main/java/org/openapitools/openapistylevalidator/rules/LicenseRule.java
- lib/src/main/java/org/openapitools/openapistylevalidator/rules/OpenAPIRule.java
- lib/src/main/java/org/openapitools/openapistylevalidator/rules/OperationDescriptionRule.java
- lib/src/main/java/org/openapitools/openapistylevalidator/rules/OperationIDRule.java
- lib/src/main/java/org/openapitools/openapistylevalidator/rules/OperationSummaryRule.java
- lib/src/main/java/org/openapitools/openapistylevalidator/rules/OperationTagRule.java
- lib/src/test/java/org/openapitools/openapistylevalidator/TestDataProvider.java
- lib/src/test/java/org/openapitools/openapistylevalidator/rules/ContactInfoRuleTest.java
- lib/src/test/java/org/openapitools/openapistylevalidator/rules/InfoDescriptionRuleTest.java
- lib/src/test/java/org/openapitools/openapistylevalidator/rules/LicenseRuleTest.java
- lib/src/test/java/org/openapitools/openapistylevalidator/rules/OpenAPIRuleTest.java
- lib/src/test/java/org/openapitools/openapistylevalidator/rules/OperationDescriptionRuleTest.java
- lib/src/test/java/org/openapitools/openapistylevalidator/rules/OperationIDRuleTest.java
- lib/src/test/java/org/openapitools/openapistylevalidator/rules/OperationSummaryRuleTest.java
- lib/src/test/java/org/openapitools/openapistylevalidator/rules/OperationTagRuleTest.java
> write existing rules as per new design.

- README.md
- lib/src/main/java/org/openapitools/openapistylevalidator/NamingValidator.java
- lib/src/main/java/org/openapitools/openapistylevalidator/ValidatorParameters.java
- lib/src/test/java/org/openapitools/openapistylevalidator/NamingValidatorTest.java
* Adds support for validating based on PascalCase.
Related to discussion [Pascal Case Support](#520) feature request.
> [#520] PascalCase Support
